// Slim shape the dashboard renders. Decoupled from the on-chain Invoice
// struct so the wire format (JSON over /api/invoices) stays stable even if
// the Anchor account layout grows new fields.

export type IndexedInvoice = {
  pda: string;
  invoiceId: string;
  totalAmount: number;
  releasedAmount: number;
  status: string;
  client: string;
  freelancer: string;
  /** Set per-row depending on which side of the lookup the wallet matched. */
  role: "freelancer" | "client";
};

export type InvoicesResponse = {
  invoices: IndexedInvoice[];
  /** ISO-8601 timestamp when this payload was generated by the server. */
  cachedAt: string;
  /** How long downstream caches should keep this payload, in seconds. */
  ttlSeconds: number;
  /** True if this payload was served from the in-process cache rather than
   *  freshly fetched from RPC. Useful for debugging cold/warm behavior. */
  fromCache: boolean;
};

export type InvoicesError = {
  error: string;
};
