import { AnchorProvider, Program, BN } from "@coral-xyz/anchor";
import { PublicKey, Keypair } from "@solana/web3.js";

import { PROGRAM_ID, INVOICE_SEED, VAULT_SEED, CONFIG_SEED } from "./constants";

// IDL is generated by `anchor build` into ../target/idl/invoiceflow.json.
// The `npm run sync-idl` script copies it here. If you see an import error,
// run that command first.
import idl from "../idl/invoiceflow.json";
import type { Invoiceflow } from "../idl/invoiceflow";

export type InvoiceflowProgram = Program<Invoiceflow>;

export function getProgram(provider: AnchorProvider): InvoiceflowProgram {
  return new Program<Invoiceflow>(idl as Invoiceflow, provider);
}

export function deriveConfigPda(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([CONFIG_SEED], PROGRAM_ID);
}

export function deriveInvoicePda(
  freelancer: PublicKey,
  invoiceId: BN
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [INVOICE_SEED, freelancer.toBuffer(), invoiceId.toArrayLike(Buffer, "le", 8)],
    PROGRAM_ID
  );
}

export function deriveVaultPda(invoice: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([VAULT_SEED, invoice.toBuffer()], PROGRAM_ID);
}

export function statusToString(status: any): string {
  if (!status) return "unknown";
  return Object.keys(status)[0] ?? "unknown";
}

/**
 * Generate a fresh per-freelancer invoice id. Uses time-based ms so collisions
 * within the same wallet are vanishingly unlikely. For a production app this
 * would be a server-side counter or an on-chain counter PDA per freelancer.
 */
export function newInvoiceId(): BN {
  return new BN(Date.now());
}
